### PR TITLE
support latest protocol changes

### PR DESCRIPTION
**Pull request by xxFLORII**

### CODE REVIEW

**Review by fuyutsuki — APPROVED** [review]
Thank you!  

I am going to make a mod after this to use GitHub Actions to build since Poggit is not building due to that is down until March.

**Comment by fuyutsuki** [comment]
↑nvm these changes

**Comment by xxFLORII** [comment]
Should I merge it, or wait?

**Comment by fuyutsuki** [comment]
I've reviewed it this time, but you can merge it without review.
Also from now on, you can merge in `dev/*.*` branch as the base branch.

**Pull request merged**
