### PR TITLE
Add support for PMMP 5.1.x

### PR DESCRIPTION
**Pull request by xxFLORII**
This PR adds support for PMMP 5.1.x. Older versions like PMMP 4.20.x are no longer supported by this update.

### CODE REVIEW

**Review by fuyutsuki — CHANGES_REQUESTED** [review]
Since there has been a minor update from Minecraft 1.19 to 1.20, I think the version of Texter should be 4.2.0.

**Comment by xxFLORII** [comment]
> Since there has been a minor update from Minecraft 1.19 to 1.20, I think the version of Texter should be 4.2.0.

Okay, should the branch also be changed to dev/4.2?

**Comment by fuyutsuki** [comment]
If you can make a dev/4.2 branch after merging this PR, there will be no problem. Thanks

**Comment by xxFLORII** [comment]
closed by #142

**Pull request closed without merging**
