### PR TITLE
Create de_DE.ini

### PR DESCRIPTION
**Pull request by DragonfireHD98**
Translate the Plugin on the Language German/Deutsch

### CODE REVIEW

**Review by xxFLORII — COMMENTED** [review]
i think it‘s better to rename the file into de_DE.ini

**Comment by DragonfireHD98** [comment]
ok

**Comment by xxFLORII** [comment]
@fuyutsuki Is this PR okay for you, or do you still have requests for changes?

**Comment by fuyutsuki** [comment]
@DragonfireHD98 Thanks for your contribution! If you change the destination to the `dev/4.1` branch and then merge it, no problem. same goes for #154!

**Comment by DragonfireHD98** [comment]
how can i do this -.- ?

**Comment by fuyutsuki** [comment]
#155 to merge so close

**Pull request closed without merging**
